<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Dashboard_model extends CI_Model {

	public function count_dashboard(){
		if ($_SESSION['logged_in']['role'] == '1') {
			$query = "SELECT (SELECT COUNT(APPROVE) FROM MST_TKI WHERE APPROVE = '0') AS COUNT_CTKI, 
			(SELECT COUNT(ID) FROM JUSTIFIKASI_PEKERJAAN WHERE STATUS = '1' AND DATA_DIRI_APPROVAL = '1' AND APPROVED_BY_1 IS NOT NULL AND ID_LOWONGAN IS NOT NULL AND (SURAT_PERJANJIAN_APPROVAL IS NULL OR SURAT_PERJANJIAN_APPROVAL = '0')) AS COUNT_PERJANJIAN_NEW,
			(SELECT COUNT(ID) FROM JUSTIFIKASI_PEKERJAAN WHERE STATUS = '1' AND DATA_DIRI_APPROVAL = '1' AND APPROVED_BY_1 IS NOT NULL AND SURAT_PERJANJIAN_APPROVAL = '1' AND APPROVED_BY_2 IS NOT NULL) AS COUNT_PERJANJIAN_APPROVED,
			(SELECT COUNT(ID) FROM JUSTIFIKASI_PEKERJAAN WHERE STATUS = '1' AND DATA_DIRI_APPROVAL = '1' AND APPROVED_BY_1 IS NOT NULL AND SURAT_PERJANJIAN_APPROVAL = '2' AND APPROVED_BY_2 IS NOT NULL) AS COUNT_PERJANJIAN_REJECTED FROM DUAL";
		} elseif ($_SESSION['logged_in']['role'] == '2') {
			$query = "SELECT
			(SELECT COUNT(ID) FROM MST_TKI WHERE APPROVE = '1' AND MAID_CODE IS NOT NULL) as TKI,
			(SELECT COUNT(ID) FROM MST_PENYALUR WHERE APPROVE = '1') as PENYALUR,
			(SELECT COUNT(ID) FROM MST_PERUSAHAAN WHERE STATUS = '1') as PERUSAHAAN FROM DUAL";
		} elseif ($_SESSION['logged_in']['role'] == '3') {
			$query = "SELECT (SELECT COUNT(APPROVE) FROM MST_TKI WHERE APPROVE = '0' AND ID_GROUP = '".$_SESSION['logged_in']['group']."') AS COUNT_CTKI, (SELECT COUNT(APPROVE) FROM MST_TKI WHERE ID_GROUP = '".$_SESSION['logged_in']['group']."') AS COUNT_TKI, (SELECT COUNT(*) FROM MST_TKI WHERE CREATED_BY = '".$_SESSION['logged_in']['id_user']."') AS MY_TKI FROM DUAL";
		} elseif ($_SESSION['logged_in']['role'] == '0') {
			
		}
		$hasil = $this->db->query($query);
		return $hasil;
	}

	public function count_dashboard2(){
		if ($_SESSION['logged_in']['role'] == '3') {
			$query = "SELECT (SELECT COUNT(APPROVE) FROM MST_TKI WHERE APPROVE = '0' AND ID_GROUP = '".$_SESSION['logged_in']['group']."') AS COUNT_CTKI, (SELECT COUNT(APPROVE) FROM MST_TKI WHERE ID_GROUP = '".$_SESSION['logged_in']['group']."') AS COUNT_TKI, (SELECT COUNT(*) FROM MST_TKI WHERE CREATED_BY = '".$_SESSION['logged_in']['id_user']."') AS MY_TKI FROM DUAL";
		} else {
			$query = "SELECT (SELECT COUNT(APPROVE) FROM MST_TKI WHERE APPROVE = '0') AS COUNT_CTKI, (SELECT COUNT(APPROVE) FROM MST_TKI WHERE APPROVE = '1') AS COUNT_TKI, (SELECT COUNT(APPROVE) FROM MST_TKI WHERE APPROVE = '2') AS COUNT_TKI_REJECTED, (SELECT COUNT(*) FROM MST_TKI) AS COUNT_TKI_ALL FROM DUAL";
		}
		$hasil = $this->db->query($query);
		return $hasil;
	}

	public function get_data_dashboard($param, $value = FALSE){
		if ($param == 'UNAPPROVECTKI') {
			$query = "SELECT a.ID, a.NAMA, c.NAMA_PERUSAHAAN FROM MST_TKI a JOIN TB_GROUP b ON a.ID_GROUP = b.ID JOIN MST_PERUSAHAAN c ON b.ID_PERUSAHAAN = c.ID WHERE a.APPROVE = '0' ORDER BY a.UPDATE_DATE DESC";
		} elseif ($param == 'NOTCREATEDPERJANJIAN') {
			$query = "SELECT a.ID as 'ID_JUSTIFIKASI', c.ID as 'ID_TKI', b.PEKERJAAN as 'PEKERJAAN', c.NAMA as 'NAMA_TKI', CONCAT(d.NAMA, ' | ', e.NAMA_PERUSAHAAN) as 'PENYALUR' FROM JUSTIFIKASI_PEKERJAAN a JOIN TB_PEKERJAAN b ON a.ID_PEKERJAAN = b.ID JOIN MST_TKI c ON a.ID_TKI = c.ID JOIN TB_USER d ON a.CREATED_BY = d.ID JOIN TB_GROUP f ON c.ID_GROUP = f.ID JOIN MST_PERUSAHAAN e ON f.ID_PERUSAHAAN = e.ID WHERE (a.STATUS = '1' AND a.DATA_DIRI_APPROVAL = '1' AND a.APPROVED_BY_1 IS NOT NULL AND ID_LOWONGAN IS NOT NULL AND (a.SURAT_PERJANJIAN_APPROVAL IS NULL OR a.SURAT_PERJANJIAN_APPROVAL = '0')) ORDER BY a.UPDATE_DATE DESC";
		} elseif ($param == 'NOTAPPROVEDTKI') {
			$query = "SELECT ID, NAMA, CONCAT(TEMPAT_LAHIR, ', ', DATE_FORMAT(TANGGAL_LAHIR, '%d %M %Y')) as 'TTL', KEWARGANEGARAAN FROM MST_TKI WHERE APPROVE = '0' AND ID_GROUP = '".$_SESSION['logged_in']['group']."'";
		} elseif ($param == 'REJECTEDTKI') {
			$query = "SELECT a.ID, a.NAMA, a.CATATAN, b.NAMA as 'NAMA_USER' FROM MST_TKI a JOIN TB_USER b ON a.APPROVED_BY = b.ID WHERE a.APPROVE = '2' AND a.ID_GROUP = '".$_SESSION['logged_in']['group']."'";
		} elseif ($param == 'UNAPPROVEPENYALUR') {
			$query = "SELECT a.ID, a.NAMA, c.NAMA_PERUSAHAAN FROM MST_PENYALUR a JOIN TB_GROUP b ON a.ID_GROUP = b.ID JOIN MST_PERUSAHAAN c ON b.ID_PERUSAHAAN = c.ID WHERE a.APPROVE = '0' ORDER BY a.UPDATE_DATE DESC";
		} elseif ($param == 'REJECTEDPENYALUR') {
			$query = "SELECT a.ID, a.NAMA, c.NAMA_PERUSAHAAN, a.CATATAN FROM MST_PENYALUR a JOIN TB_GROUP b ON a.ID_GROUP = b.ID JOIN MST_PERUSAHAAN c ON b.ID_PERUSAHAAN = c.ID WHERE a.APPROVE = '2' ORDER BY a.UPDATE_DATE DESC";
		} elseif ($param == 'UNAPPROVEPERJANJIANTAB') {
			$query = "SELECT a.ID as 'ID_JUSTIFIKASI', c.ID as 'ID_TKI', b.PEKERJAAN as 'PEKERJAAN', c.NAMA as 'NAMA_TKI', CONCAT(d.NAMA, ' | ', e.NAMA_PERUSAHAAN) as 'PENYALUR' FROM JUSTIFIKASI_PEKERJAAN a JOIN TB_PEKERJAAN b ON a.ID_PEKERJAAN = b.ID JOIN MST_TKI c ON a.ID_TKI = c.ID JOIN TB_USER d ON a.CREATED_BY = d.ID JOIN TB_GROUP f ON c.ID_GROUP = f.ID JOIN MST_PERUSAHAAN e ON f.ID_PERUSAHAAN = e.ID WHERE (a.STATUS = '1' AND a.DATA_DIRI_APPROVAL = '1' AND a.APPROVED_BY_1 IS NOT NULL AND ID_LOWONGAN IS NOT NULL AND a.SURAT_PERJANJIAN_APPROVAL = '3') ORDER BY a.UPDATE_DATE DESC";
		} elseif ($param == 'REJECTEDPERJANJIANTAB') {
			$query = "SELECT a.ID as 'ID_JUSTIFIKASI', c.ID as 'ID_TKI', b.PEKERJAAN as 'PEKERJAAN', c.NAMA as 'NAMA_TKI', CONCAT(d.NAMA, ' | ', e.NAMA_PERUSAHAAN) as 'PENYALUR', g.CATATAN FROM JUSTIFIKASI_PEKERJAAN a JOIN TB_PEKERJAAN b ON a.ID_PEKERJAAN = b.ID JOIN MST_TKI c ON a.ID_TKI = c.ID JOIN TB_USER d ON a.CREATED_BY = d.ID JOIN TB_GROUP f ON c.ID_GROUP = f.ID JOIN MST_PERUSAHAAN e ON f.ID_PERUSAHAAN = e.ID JOIN TB_SURAT_PERJANJIAN g ON a.ID_PERJANJIAN = g.ID WHERE (a.STATUS = '1' AND a.DATA_DIRI_APPROVAL = '1' AND a.APPROVED_BY_1 IS NOT NULL AND ID_LOWONGAN IS NOT NULL AND a.SURAT_PERJANJIAN_APPROVAL = '2') ORDER BY a.UPDATE_DATE DESC";
		} elseif ($param == 'NOTCREATEDKONTRAK') {
			$query = "SELECT a.ID as 'ID_JUSTIFIKASI', c.ID as 'ID_TKI', b.PEKERJAAN as 'PEKERJAAN', c.NAMA as 'NAMA_TKI', CONCAT(d.NAMA, ' | ', e.NAMA_PERUSAHAAN) as 'PENYALUR', g.CATATAN FROM JUSTIFIKASI_PEKERJAAN a JOIN TB_PEKERJAAN b ON a.ID_PEKERJAAN = b.ID JOIN MST_TKI c ON a.ID_TKI = c.ID JOIN TB_USER d ON a.CREATED_BY = d.ID JOIN TB_GROUP f ON c.ID_GROUP = f.ID JOIN MST_PERUSAHAAN e ON f.ID_PERUSAHAAN = e.ID JOIN TB_KONTRAK g ON a.ID_KONTRAK = g.ID WHERE (a.STATUS = '1' AND a.DATA_DIRI_APPROVAL = '1' AND a.APPROVED_BY_1 IS NOT NULL AND ID_LOWONGAN IS NOT NULL AND (a.KONTRAK_KERJA_APPROVAL IS NULL OR a.KONTRAK_KERJA_APPROVAL = '0')) ORDER BY a.UPDATE_DATE DESC";
		} elseif ($param == 'REJECTEDKONTRAK') {
			$query = "SELECT a.ID as 'ID_JUSTIFIKASI', c.ID as 'ID_TKI', b.PEKERJAAN as 'PEKERJAAN', (SELECT NAMA FROM TB_USER WHERE ID = a.APPROVED_BY_3) as 'APPROVED_BY', c.NAMA as 'NAMA_TKI', CONCAT(d.NAMA, ' | ', e.NAMA_PERUSAHAAN) as 'PENYALUR', g.CATATAN FROM JUSTIFIKASI_PEKERJAAN a JOIN TB_PEKERJAAN b ON a.ID_PEKERJAAN = b.ID JOIN MST_TKI c ON a.ID_TKI = c.ID JOIN TB_USER d ON a.CREATED_BY = d.ID JOIN TB_GROUP f ON c.ID_GROUP = f.ID JOIN MST_PERUSAHAAN e ON f.ID_PERUSAHAAN = e.ID JOIN TB_KONTRAK g ON a.ID_KONTRAK = g.ID WHERE (a.STATUS = '1' AND a.DATA_DIRI_APPROVAL = '1' AND a.APPROVED_BY_1 IS NOT NULL AND ID_LOWONGAN IS NOT NULL AND a.KONTRAK_KERJA_APPROVAL = '2') ORDER BY a.UPDATE_DATE DESC";
		} elseif ($param == 'NOTCREATEDPEKERJAAN') {
			$query = "SELECT a.ID as 'ID_JUSTIFIKASI', c.ID as 'ID_TKI', b.PEKERJAAN as 'PEKERJAAN', c.NAMA as 'NAMA_TKI', CONCAT(d.NAMA, ' | ', e.NAMA_PERUSAHAAN) as 'PENYALUR'FROM JUSTIFIKASI_PEKERJAAN a JOIN TB_PEKERJAAN b ON a.ID_PEKERJAAN = b.ID JOIN MST_TKI c ON a.ID_TKI = c.ID JOIN TB_USER d ON a.CREATED_BY = d.ID JOIN TB_GROUP f ON c.ID_GROUP = f.ID JOIN MST_PERUSAHAAN e ON f.ID_PERUSAHAAN = e.ID WHERE (a.STATUS = '1' AND a.DATA_DIRI_APPROVAL = '1' AND a.APPROVED_BY_1 IS NOT NULL AND ID_LOWONGAN IS NULL) ORDER BY a.UPDATE_DATE DESC";
		} elseif ($param == 'APPROVEPERJANJIAN') {
			$query = "SELECT a.ID as 'ID_JUSTIFIKASI', c.ID as 'ID_TKI', b.PEKERJAAN as 'PEKERJAAN', (SELECT NAMA FROM TB_USER WHERE ID = a.APPROVED_BY_3) as 'APPROVED_BY', c.NAMA as 'NAMA_TKI', (SELECT NAMA FROM TB_USER WHERE ID = g.CREATED_BY) as 'CREATED_BY' FROM JUSTIFIKASI_PEKERJAAN a JOIN TB_PEKERJAAN b ON a.ID_PEKERJAAN = b.ID JOIN MST_TKI c ON a.ID_TKI = c.ID JOIN TB_USER d ON a.CREATED_BY = d.ID JOIN TB_GROUP f ON c.ID_GROUP = f.ID JOIN MST_PERUSAHAAN e ON f.ID_PERUSAHAAN = e.ID JOIN TB_SURAT_PERJANJIAN g ON a.ID_PERJANJIAN = g.ID WHERE (a.STATUS = '1' AND a.DATA_DIRI_APPROVAL = '1' AND a.APPROVED_BY_1 IS NOT NULL AND ID_LOWONGAN IS NOT NULL AND a.SURAT_PERJANJIAN_APPROVAL = '3' AND c.ID_GROUP = '".$_SESSION['logged_in']['group']."') ORDER BY a.UPDATE_DATE DESC";
		} elseif ($param == 'APPROVEKONTRAK') {
			$query = "SELECT a.ID as 'ID_JUSTIFIKASI', c.ID as 'ID_TKI', b.PEKERJAAN as 'PEKERJAAN', (SELECT NAMA FROM TB_USER WHERE ID = a.APPROVED_BY_3) as 'APPROVED_BY', c.NAMA as 'NAMA_TKI', (SELECT NAMA FROM TB_USER WHERE ID = g.CREATED_BY) as 'CREATED_BY' FROM JUSTIFIKASI_PEKERJAAN a JOIN TB_PEKERJAAN b ON a.ID_PEKERJAAN = b.ID JOIN MST_TKI c ON a.ID_TKI = c.ID JOIN TB_USER d ON a.CREATED_BY = d.ID JOIN TB_GROUP f ON c.ID_GROUP = f.ID JOIN MST_PERUSAHAAN e ON f.ID_PERUSAHAAN = e.ID JOIN TB_KONTRAK g ON a.ID_KONTRAK = g.ID WHERE (a.STATUS = '1' AND a.DATA_DIRI_APPROVAL = '1' AND a.APPROVED_BY_1 IS NOT NULL AND ID_LOWONGAN IS NOT NULL AND a.KONTRAK_KERJA_APPROVAL = '3' AND c.ID_GROUP = '".$_SESSION['logged_in']['group']."') ORDER BY a.UPDATE_DATE DESC";
		} elseif ($param == 'AUDIT') {
			$query = "SELECT b.JENIS, (SELECT NAMA FROM TB_USER WHERE ID = a.ID_USER) as 'USER', SUBSTRING(a.CATATAN, 1,80) as 'CATATAN', a.INSERT_DATE FROM LOG a JOIN TB_RULE_ACT b ON a.JENIS = b.ID WHERE a.STATUS = '1' ORDER BY a.INSERT_DATE DESC LIMIT 100";
		} elseif ($param == 'AUDITPARAM') {
			$query = "SELECT b.JENIS, (SELECT NAMA FROM TB_USER WHERE ID = a.ID_USER) as 'USER', SUBSTRING(a.CATATAN, 1,80) as 'CATATAN', a.INSERT_DATE FROM LOG a JOIN TB_RULE_ACT b ON a.JENIS = b.ID WHERE a.ID_USER = '".$value."' ORDER BY a.INSERT_DATE DESC";
		} else {
			$query = "SELECT 1 FROM DUAL;";
		}
		$hasil = $this->db->query($query);
		return $hasil;
	}

	public function get_count_job(){
		if ($_SESSION['logged_in']['role'] == '3') {
			$query = "SELECT
			(SELECT COUNT(a.ID) FROM JUSTIFIKASI_PEKERJAAN a JOIN MST_TKI b ON a.ID_TKI = b.ID WHERE (a.STATUS = '1' AND b.ID_GROUP = '".$_SESSION['logged_in']['group']."')) aS PEKERJAAN_AKTIF,
			(SELECT COUNT(a.ID) FROM JUSTIFIKASI_PEKERJAAN a JOIN MST_TKI b ON a.ID_TKI = b.ID WHERE (a.STATUS = '0' AND a.PROGRESS = '0') AND b.ID_GROUP = '".$_SESSION['logged_in']['group']."') AS PEKERJAAN_SELESAI,
			(SELECT COUNT(a.ID) FROM JUSTIFIKASI_PEKERJAAN a JOIN MST_TKI b ON a.ID_TKI = b.ID WHERE (a.STATUS = '0' AND a.PROGRESS = '5') AND b.ID_GROUP = '".$_SESSION['logged_in']['group']."') AS PEKERJAAN_DIBATALKAN,
			(SELECT COUNT(a.ID) FROM JUSTIFIKASI_PEKERJAAN a JOIN MST_TKI b ON a.ID_TKI = b.ID WHERE (b.ID_GROUP = '".$_SESSION['logged_in']['group']."')) AS TOTAL_PEKERJAAN FROM DUAL";
		} else {
			$query = "SELECT
			(SELECT COUNT(ID) FROM JUSTIFIKASI_PEKERJAAN WHERE STATUS = '1') AS PEKERJAAN_AKTIF,
			(SELECT COUNT(ID) FROM JUSTIFIKASI_PEKERJAAN WHERE STATUS = '0' AND PROGRESS = '0') AS PEKERJAAN_SELESAI,
			(SELECT COUNT(ID) FROM JUSTIFIKASI_PEKERJAAN WHERE STATUS = '0' AND PROGRESS = '5') AS PEKERJAAN_DIBATALKAN,
			(SELECT COUNT(ID) FROM JUSTIFIKASI_PEKERJAAN) AS TOTAL_PEKERJAAN FROM DUAL";
		}
		$hasil = $this->db->query($query);
		return $hasil;
	}
}